### ISSUE TITLE
[Feature] output the cluster autoscaler helm values file

### ISSUE THREAD

**Issue by sblack4** [rhythmictech/terraform-aws-eks-iam-cluster-autoscaler#4]
output the cluster autoscaler helm chart values file from a template like this 

```
awsRegion: us-east-1
cloudProvider: aws

rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${iam_role_arn}"

autoDiscovery:
  clusterName: ${cluster_name}
  enabled: true
```
